---
abstract: 'Extract Raw Chunks of data from identifiable ELF Sections'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ELF-Extract-Sections
provides:
  ELF::Extrac::Sections::Scanner::Objdump:
    file: lib/ELF/Extract/Sections/Scanner/Objdump.pm
    version: 0.0103
  ELF::Extract::Sections:
    file: lib/ELF/Extract/Sections.pm
    version: 0.0103
  ELF::Extract::Sections::Meta::Scanner:
    file: lib/ELF/Extract/Sections/Meta/Scanner.pm
    version: 0.0103
  ELF::Extract::Sections::Meta::Types:
    file: lib/ELF/Extract/Sections/Meta/Types.pm
    version: 0.0103
  ELF::Extract::Sections::Scanner::Objdump:
    file: lib/ELF/Extract/Sections/Scanner/Objdump.pm
    version: 0.0103
  ELF::Extract::Sections::Section:
    file: lib/ELF/Extract/Sections/Section.pm
    version: 0.0103
requires:
  File::Find::Rule: 0
  FindBin: 0
  Log::Log4perl: 1.21
  Moose: 0.76
  Moose::Role: 0
  MooseX::Declare: 0.20
  MooseX::Has::Sugar: 0.0300
  MooseX::Log::Log4perl: 0.31
  MooseX::Types: 0
  MooseX::Types::Moose: 0.10
  MooseX::Types::Path::Class: 0.05
  Path::Class: 0
  Test::More: 0
  YAML::XS: 0
  lib: 0
  overload: 0
resources:
  repository: git://github.com/kentfredric/ELF-Extract-Sections.git
version: 0.0103
