---
abstract: 'Extract Raw Chunks of data from identifiable ELF Sections'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Log::Log4perl: '1.21'
  Path::Iterator::Rule: '0'
  Path::Tiny: '0'
  Test::More: '0.89'
  YAML::XS: '0'
  lib: '0'
  perl: '5.010000'
configure_requires:
  Devel::CheckBin: '0'
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ELF-Extract-Sections
provides:
  ELF::Extract::Sections:
    file: lib/ELF/Extract/Sections.pm
    version: '1.000000'
  ELF::Extract::Sections::Meta::Scanner:
    file: lib/ELF/Extract/Sections/Meta/Scanner.pm
    version: '1.000000'
  ELF::Extract::Sections::Meta::Types:
    file: lib/ELF/Extract/Sections/Meta/Types.pm
    version: '1.000000'
  ELF::Extract::Sections::Scanner::Objdump:
    file: lib/ELF/Extract/Sections/Scanner/Objdump.pm
    version: '1.000000'
  ELF::Extract::Sections::Section:
    file: lib/ELF/Extract/Sections/Section.pm
    version: '1.000000'
recommends:
  Moose: '2.000'
requires:
  Carp: '0'
  Class::Load: '0'
  Log::Log4perl: '1.21'
  Moose: '0.76'
  Moose::Role: '0'
  MooseX::Declare: '0.20'
  MooseX::Has::Sugar: '0.0300'
  MooseX::Log::Log4perl: '0.31'
  MooseX::Types: '0.10'
  MooseX::Types::Moose: '0.10'
  MooseX::Types::Path::Tiny: '0'
  overload: '0'
  perl: '5.010000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/ELF-Extract-Sections/issues
  homepage: https://github.com/kentnl/ELF-Extract-Sections
  repository: https://github.com/kentnl/ELF-Extract-Sections.git
version: '1.000000'
